python scripts/0_precalculate_proteins.py
python scripts/0_precalculate_proteins_only_slc_aucs.py
python scripts/1_experimental_validation_predictions.py
python scripts/1_experimental_validation_predictions_groups.py
python scripts/2_gsf_predictions.py
python scripts/2_chembl_predictions.py
python scripts/2_gsf_predictions_groups.py 0
python scripts/2_chembl_predictions_groups.py 0
python scripts/2_chembl_predictions.py 1
python scripts/2_chembl_predictions_groups.py 1
python scripts/2_chembl_predictions.py 2
python scripts/2_chembl_predictions_groups.py 2
